from __future__ import annotations

from open_vernacular_ai_kit.language_packs import get_language_pack


def test_language_profiles_load_from_packaged_data() -> None:
    gu = get_language_pack("gu")
    hi = get_language_pack("hi")

    assert gu.default_exceptions["tamaro"] == "તમારો"
    assert gu.default_exceptions["ma"] == "માં"
    assert "ma" in gu.context_roman_tokens

    assert hi.default_exceptions["mera"] == "मेरा"
    assert hi.default_exceptions["me"] == "में"
    assert "me" in hi.context_roman_tokens

    assert hi.default_exceptions["dijiye"] == "दीजिए"
    assert hi.default_exceptions["madad"] == "मदद"
    assert hi.default_exceptions["bhej"] == "भेज"
    assert hi.default_exceptions["lekin"] == "लेकिन"
    assert gu.default_exceptions["chhiye"] == "છીએ"
    assert gu.default_exceptions["aavo"] == "આવો"
    assert gu.default_exceptions["paisa"] == "પૈસા"
    assert gu.default_exceptions["avse"] == "આવશે"
    assert gu.default_exceptions["tamare"] == "તમારે"
    assert gu.default_exceptions["aa"] == "આ"
    assert gu.default_exceptions["fari"] == "ફરી"
    assert gu.default_exceptions["ni"] == "ની"
    assert gu.default_exceptions["nu"] == "નું"
    assert gu.default_exceptions["vage"] == "વાગે"
    assert gu.default_exceptions["jagyae"] == "જગ્યાએ"
    assert gu.default_exceptions["sathe"] == "સાથે"
    assert gu.default_exceptions["ochhu"] == "ઓછું"
    assert gu.default_exceptions["etle"] == "એટલે"
    assert gu.default_exceptions["pela"] == "પહેલા"
    assert gu.default_exceptions["paise"] == "પૈસા"
    assert gu.default_exceptions["malyo"] == "મળ્યો"
    assert gu.default_exceptions["batave"] == "બતાવે"
    assert gu.default_exceptions["avsho"] == "આવશો"
    assert gu.default_exceptions["atki"] == "અટકી"
    assert gu.default_exceptions["moklo"] == "મોકલો"
    assert gu.default_exceptions["karto"] == "કરતો"
    assert gu.default_exceptions["karvu"] == "કરવું"
    assert gu.default_exceptions["kare"] == "કરે"
    assert gu.default_exceptions["rakhjo"] == "રાખજો"
    assert gu.default_exceptions["chhata"] == "છતાં"
    assert gu.default_exceptions["atkyu"] == "અટક્યું"
    assert gu.default_exceptions["turant"] == "તુરંત"
    assert gu.default_exceptions["thase"] == "થશે"
    assert gu.default_exceptions["rakho"] == "રાખો"
    assert gu.default_exceptions["padse"] == "પડશે"
    assert gu.default_exceptions["thato"] == "થતો"
    assert gu.default_exceptions["karjo"] == "કરજો"
    assert gu.default_exceptions["krjo"] == "કરજો"
    assert gu.default_exceptions["chu"] == "છું"
    assert gu.default_exceptions["pohnchyoo"] == "પહોંચ્યો"
    assert gu.default_exceptions["bapor"] == "બપોર"
    assert gu.default_exceptions["thayu"] == "થયું"
    assert gu.default_exceptions["aavyo"] == "આવ્યો"
    assert gu.default_exceptions["javun"] == "જવું"
    assert gu.default_exceptions["ochha"] == "ઓછા"
    assert gu.default_exceptions["dubara"] == "ફરીથી"
    assert gu.default_exceptions["vishe"] == "વિશે"
    assert gu.default_exceptions["niche"] == "નીચે"
    assert gu.default_exceptions["thi"] == "થી"
    assert gu.default_exceptions["chale"] == "ચાલે"
    assert gu.default_exceptions["sudhi"] == "સુધી"
    assert gu.default_exceptions["moklyo"] == "મોકલ્યો"
    assert gu.default_exceptions["badha"] == "બધા"
    assert gu.default_exceptions["mne"] == "મને"
    assert gu.default_exceptions["je"] == "જે"
    assert gu.default_exceptions["jyare"] == "જ્યારે"
    assert gu.default_exceptions["joiye"] == "જોઈએ"
    assert gu.default_exceptions["gaya"] == "ગયા"
    assert gu.default_exceptions["aavse"] == "આવશે"
    assert gu.default_exceptions["samajhatu"] == "સમજાતું"
    assert gu.default_exceptions["batavyu"] == "બતાવ્યું"
    assert gu.default_exceptions["ochho"] == "ઓછો"
    assert gu.default_exceptions["jaldi"] == "જલ્દી"
    assert gu.default_exceptions["aapo"] == "આપો"
    assert gu.default_exceptions["adhuro"] == "અધૂરો"
    assert gu.default_exceptions["badhu"] == "બધું"
    assert gu.default_exceptions["be"] == "બે"
    assert gu.default_exceptions["bijo"] == "બીજો"
    assert gu.default_exceptions["dekhatu"] == "દેખાતું"
    assert gu.default_exceptions["didhu"] == "દીધું"
    assert gu.default_exceptions["htu"] == "હતું"
    assert gu.default_exceptions["aavya"] == "આવ્યા"
    assert gu.default_exceptions["mathi"] == "માંથી"
    assert gu.default_exceptions["mate"] == "માટે"
    assert gu.default_exceptions["haju"] == "હજુ"
    assert gu.default_exceptions["vagar"] == "વગર"
    assert "tamare" in gu.common_roman_tokens
    assert "aa" in gu.common_roman_tokens
    assert "fari" in gu.common_roman_tokens
    assert "jagyae" in gu.common_roman_tokens
    assert "ochhu" in gu.common_roman_tokens
    assert "paise" in gu.common_roman_tokens
    assert "moklo" in gu.common_roman_tokens
    assert "karto" in gu.common_roman_tokens
    assert "karvu" in gu.common_roman_tokens
    assert "kare" in gu.common_roman_tokens
    assert "rakhjo" in gu.common_roman_tokens
    assert "chhata" in gu.common_roman_tokens
    assert "atkyu" in gu.common_roman_tokens
    assert "turant" in gu.common_roman_tokens
    assert "thase" in gu.common_roman_tokens
    assert "rakho" in gu.common_roman_tokens
    assert "padse" in gu.common_roman_tokens
    assert "thato" in gu.common_roman_tokens
    assert "karjo" in gu.common_roman_tokens
    assert "krjo" in gu.common_roman_tokens
    assert "chu" in gu.common_roman_tokens
    assert "pohnchyoo" in gu.common_roman_tokens
    assert "thayu" in gu.common_roman_tokens
    assert "aavyo" in gu.common_roman_tokens
    assert "javun" in gu.common_roman_tokens
    assert "ochha" in gu.common_roman_tokens
    assert "niche" in gu.common_roman_tokens
    assert "chale" in gu.common_roman_tokens
    assert "moklyo" in gu.common_roman_tokens
    assert "badha" in gu.common_roman_tokens
    assert "mne" in gu.common_roman_tokens
    assert "joiye" in gu.common_roman_tokens
    assert "gaya" in gu.common_roman_tokens
    assert "aavse" in gu.common_roman_tokens
    assert "samajhatu" in gu.common_roman_tokens
    assert "batavyu" in gu.common_roman_tokens
    assert "ochho" in gu.common_roman_tokens
    assert "jaldi" in gu.common_roman_tokens
    assert "aapo" in gu.common_roman_tokens
    assert "adhuro" in gu.common_roman_tokens
    assert "badhu" in gu.common_roman_tokens
    assert "be" in gu.common_roman_tokens
    assert "bijo" in gu.common_roman_tokens
    assert "dekhatu" in gu.common_roman_tokens
    assert "didhu" in gu.common_roman_tokens
    assert "htu" in gu.common_roman_tokens
    assert "aavya" in gu.common_roman_tokens
    assert "ni" in gu.context_roman_tokens
    assert "nu" in gu.context_roman_tokens
    assert "sathe" in gu.context_roman_tokens
    assert "etle" in gu.context_roman_tokens
    assert "pela" in gu.context_roman_tokens
    assert "mate" in gu.context_roman_tokens
    assert "haju" in gu.context_roman_tokens
    assert "vagar" in gu.context_roman_tokens
    assert "bapor" in gu.context_roman_tokens
    assert "dubara" in gu.context_roman_tokens
    assert "vishe" in gu.context_roman_tokens
    assert "thi" in gu.context_roman_tokens
    assert "sudhi" in gu.context_roman_tokens
    assert "mathi" in gu.context_roman_tokens
    assert "je" in gu.context_roman_tokens
    assert "jyare" in gu.context_roman_tokens
    assert "lekin" in hi.common_roman_tokens
    assert hi.default_exceptions["dobara"] == "दोबारा"
    assert hi.default_exceptions["abhi"] == "अभी"
    assert hi.default_exceptions["galat"] == "गलत"
    assert hi.default_exceptions["batayiye"] == "बताइए"
    assert hi.default_exceptions["kyon"] == "क्यों"
    assert hi.default_exceptions["bhejo"] == "भेजो"
    assert hi.default_exceptions["subah"] == "सुबह"
    assert hi.default_exceptions["mila"] == "मिला"
    assert hi.default_exceptions["niche"] == "नीचे"
    assert hi.default_exceptions["turant"] == "तुरंत"
    assert hi.default_exceptions["padega"] == "पड़ेगा"
    assert hi.default_exceptions["isliye"] == "इसलिए"
    assert hi.default_exceptions["jaldi"] == "जल्दी"
    assert hi.default_exceptions["bilkul"] == "बिल्कुल"
    assert hi.default_exceptions["dubara"] == "दुबारा"
    assert hi.default_exceptions["dopahar"] == "दोपहर"
    assert hi.default_exceptions["baar"] == "बार"
    assert hi.default_exceptions["do"] == "दो"
    assert hi.default_exceptions["jo"] == "जो"
    assert hi.default_exceptions["kyunki"] == "क्योंकि"
    assert hi.default_exceptions["aj"] == "आज"
    assert hi.default_exceptions["tk"] == "तक"
    assert hi.default_exceptions["baad"] == "बाद"
    assert "galat" in hi.common_roman_tokens
    assert "batayiye" in hi.common_roman_tokens
    assert "kyon" in hi.common_roman_tokens
    assert "bhejo" in hi.common_roman_tokens
    assert "subah" in hi.common_roman_tokens
    assert "mila" in hi.common_roman_tokens
    assert "turant" in hi.common_roman_tokens
    assert "padega" in hi.common_roman_tokens
    assert "jaldi" in hi.common_roman_tokens
    assert "bilkul" in hi.common_roman_tokens
    assert "dubara" in hi.common_roman_tokens
    assert "dopahar" in hi.common_roman_tokens
    assert "baar" in hi.common_roman_tokens
    assert "do" in hi.common_roman_tokens
    assert "dobara" in hi.context_roman_tokens
    assert "abhi" in hi.context_roman_tokens
    assert "niche" in hi.context_roman_tokens
    assert "isliye" in hi.context_roman_tokens
    assert "aj" in hi.context_roman_tokens
    assert "tk" in hi.context_roman_tokens
    assert "baad" in hi.context_roman_tokens
    assert "jo" in hi.context_roman_tokens
    assert "kyunki" in hi.context_roman_tokens
